//
//  EnemyDispatchConfig.h
//  BlackWings
//
//  Created by Jacky on 14-6-29.
//
//

#ifndef __BlackWings__EnemyDispatchConfig__
#define __BlackWings__EnemyDispatchConfig__

#include "Configuration.h"

//normal enemy waves
#define STAGE_ENEMY_WAVES_00 1
#define STAGE_ENEMY_WAVES_01 1
#define STAGE_ENEMY_WAVES_02 3
#define STAGE_ENEMY_WAVES_03 3
#define STAGE_ENEMY_WAVES_04 3
#define STAGE_ENEMY_WAVES_05 3
#define STAGE_ENEMY_WAVES_06 3
#define STAGE_ENEMY_WAVES_07 3
#define STAGE_ENEMY_WAVES_08 3
#define STAGE_ENEMY_WAVES_09 3
#define STAGE_ENEMY_WAVES_10 3
#define STAGE_ENEMY_WAVES_11 3
#define STAGE_ENEMY_WAVES_12 3
#define STAGE_ENEMY_WAVES_13 3
#define STAGE_ENEMY_WAVES_14 3
#define STAGE_ENEMY_WAVES_15 3
#define STAGE_ENEMY_WAVES_16 3
#define STAGE_ENEMY_WAVES_17 3
#define STAGE_ENEMY_WAVES_18 3
#define STAGE_ENEMY_WAVES_19 3
#define STAGE_ENEMY_WAVES_20 3
#define STAGE_ENEMY_WAVES_21 3
#define STAGE_ENEMY_WAVES_22 3
#define STAGE_ENEMY_WAVES_23 3
#define STAGE_ENEMY_WAVES_24 3
#define STAGE_ENEMY_WAVES_25 3
#define STAGE_ENEMY_WAVES_26 3
#define STAGE_ENEMY_WAVES_27 3
#define STAGE_ENEMY_WAVES_28 3
#define STAGE_ENEMY_WAVES_29 3
#define STAGE_ENEMY_WAVES_30 3
#define STAGE_ENEMY_WAVES_31 3
#define STAGE_ENEMY_WAVES_32 3
#define STAGE_ENEMY_WAVES_33 3
#define STAGE_ENEMY_WAVES_34 3
#define STAGE_ENEMY_WAVES_35 3
#define STAGE_ENEMY_WAVES_36 3
#define STAGE_ENEMY_WAVES_37 3
#define STAGE_ENEMY_WAVES_38 3
#define STAGE_ENEMY_WAVES_39 3
#define STAGE_ENEMY_WAVES_40 3
#define STAGE_ENEMY_WAVES_41 3
#define STAGE_ENEMY_WAVES_42 3
#define STAGE_ENEMY_WAVES_43 3
#define STAGE_ENEMY_WAVES_44 3
#define STAGE_ENEMY_WAVES_45 3
#define STAGE_ENEMY_WAVES_46 3
#define STAGE_ENEMY_WAVES_47 3
#define STAGE_ENEMY_WAVES_48 3
#define STAGE_ENEMY_WAVES_49 3

//towerCount
#define STAGE_TOWER_COUNTS_00 1
#define STAGE_TOWER_COUNTS_01 1
#define STAGE_TOWER_COUNTS_02 2
#define STAGE_TOWER_COUNTS_03 2
#define STAGE_TOWER_COUNTS_04 2
#define STAGE_TOWER_COUNTS_05 2
#define STAGE_TOWER_COUNTS_06 2
#define STAGE_TOWER_COUNTS_07 2
#define STAGE_TOWER_COUNTS_08 2
#define STAGE_TOWER_COUNTS_09 2
#define STAGE_TOWER_COUNTS_10 2
#define STAGE_TOWER_COUNTS_11 2
#define STAGE_TOWER_COUNTS_12 2
#define STAGE_TOWER_COUNTS_13 2
#define STAGE_TOWER_COUNTS_14 2
#define STAGE_TOWER_COUNTS_15 2
#define STAGE_TOWER_COUNTS_16 2
#define STAGE_TOWER_COUNTS_17 2
#define STAGE_TOWER_COUNTS_18 2
#define STAGE_TOWER_COUNTS_19 2
#define STAGE_TOWER_COUNTS_20 2
#define STAGE_TOWER_COUNTS_21 2
#define STAGE_TOWER_COUNTS_22 2
#define STAGE_TOWER_COUNTS_23 2
#define STAGE_TOWER_COUNTS_24 2
#define STAGE_TOWER_COUNTS_25 2
#define STAGE_TOWER_COUNTS_26 2
#define STAGE_TOWER_COUNTS_27 2
#define STAGE_TOWER_COUNTS_28 2
#define STAGE_TOWER_COUNTS_29 2
#define STAGE_TOWER_COUNTS_30 2
#define STAGE_TOWER_COUNTS_31 2
#define STAGE_TOWER_COUNTS_32 2
#define STAGE_TOWER_COUNTS_33 2
#define STAGE_TOWER_COUNTS_34 2
#define STAGE_TOWER_COUNTS_35 2
#define STAGE_TOWER_COUNTS_36 2
#define STAGE_TOWER_COUNTS_37 2
#define STAGE_TOWER_COUNTS_38 2
#define STAGE_TOWER_COUNTS_39 2
#define STAGE_TOWER_COUNTS_40 2
#define STAGE_TOWER_COUNTS_41 2
#define STAGE_TOWER_COUNTS_42 2
#define STAGE_TOWER_COUNTS_43 2
#define STAGE_TOWER_COUNTS_44 2
#define STAGE_TOWER_COUNTS_45 2
#define STAGE_TOWER_COUNTS_46 2
#define STAGE_TOWER_COUNTS_47 2
#define STAGE_TOWER_COUNTS_48 2
#define STAGE_TOWER_COUNTS_49 2

//NormalEnemy
typedef struct _battleNormalEnemyConfig
{
    int duration;
    int type;
    int level;
    int count;
}BattleNormalEnemyConfig;

typedef struct _battleNormalEnemyInfo
{
    BattleNormalEnemyConfig* _bnec;
    int waves;
}BattleNormalEnemyInfo;

extern BattleNormalEnemyInfo s_battleNormalEnemyInfo[STAGE_COUNT];

extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_0[STAGE_ENEMY_WAVES_00];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_1[STAGE_ENEMY_WAVES_01];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_2[STAGE_ENEMY_WAVES_02];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_3[STAGE_ENEMY_WAVES_03];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_4[STAGE_ENEMY_WAVES_04];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_5[STAGE_ENEMY_WAVES_05];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_6[STAGE_ENEMY_WAVES_06];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_7[STAGE_ENEMY_WAVES_07];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_8[STAGE_ENEMY_WAVES_08];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_9[STAGE_ENEMY_WAVES_09];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_10[STAGE_ENEMY_WAVES_10];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_11[STAGE_ENEMY_WAVES_11];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_12[STAGE_ENEMY_WAVES_12];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_13[STAGE_ENEMY_WAVES_13];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_14[STAGE_ENEMY_WAVES_14];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_15[STAGE_ENEMY_WAVES_15];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_16[STAGE_ENEMY_WAVES_16];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_17[STAGE_ENEMY_WAVES_17];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_18[STAGE_ENEMY_WAVES_18];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_19[STAGE_ENEMY_WAVES_19];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_20[STAGE_ENEMY_WAVES_20];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_21[STAGE_ENEMY_WAVES_21];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_22[STAGE_ENEMY_WAVES_22];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_23[STAGE_ENEMY_WAVES_23];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_24[STAGE_ENEMY_WAVES_24];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_25[STAGE_ENEMY_WAVES_25];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_26[STAGE_ENEMY_WAVES_26];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_27[STAGE_ENEMY_WAVES_27];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_28[STAGE_ENEMY_WAVES_28];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_29[STAGE_ENEMY_WAVES_29];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_30[STAGE_ENEMY_WAVES_30];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_31[STAGE_ENEMY_WAVES_31];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_32[STAGE_ENEMY_WAVES_32];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_33[STAGE_ENEMY_WAVES_33];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_34[STAGE_ENEMY_WAVES_34];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_35[STAGE_ENEMY_WAVES_35];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_36[STAGE_ENEMY_WAVES_36];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_37[STAGE_ENEMY_WAVES_37];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_38[STAGE_ENEMY_WAVES_38];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_39[STAGE_ENEMY_WAVES_39];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_40[STAGE_ENEMY_WAVES_40];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_41[STAGE_ENEMY_WAVES_41];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_42[STAGE_ENEMY_WAVES_42];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_43[STAGE_ENEMY_WAVES_43];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_44[STAGE_ENEMY_WAVES_44];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_45[STAGE_ENEMY_WAVES_45];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_46[STAGE_ENEMY_WAVES_46];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_47[STAGE_ENEMY_WAVES_47];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_48[STAGE_ENEMY_WAVES_48];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_49[STAGE_ENEMY_WAVES_49];

//TowerEnemy
typedef struct _battleTowerEnemyConfig
{
    int level;
    int x;
    int y;
}BattleTowerEnemyConfig;

typedef struct _battleTowerEnemyInfo
{
    BattleTowerEnemyConfig* _btec;
    int counts;
}BattleTowerEnemyInfo;

extern BattleTowerEnemyInfo s_battleTowerEnemyInfo[STAGE_COUNT];

extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_0[STAGE_TOWER_COUNTS_00];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_1[STAGE_TOWER_COUNTS_01];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_2[STAGE_TOWER_COUNTS_02];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_3[STAGE_TOWER_COUNTS_03];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_4[STAGE_TOWER_COUNTS_04];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_5[STAGE_TOWER_COUNTS_05];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_6[STAGE_TOWER_COUNTS_06];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_7[STAGE_TOWER_COUNTS_07];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_8[STAGE_TOWER_COUNTS_08];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_9[STAGE_TOWER_COUNTS_09];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_10[STAGE_TOWER_COUNTS_10];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_11[STAGE_TOWER_COUNTS_11];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_12[STAGE_TOWER_COUNTS_12];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_13[STAGE_TOWER_COUNTS_13];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_14[STAGE_TOWER_COUNTS_14];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_15[STAGE_TOWER_COUNTS_15];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_16[STAGE_TOWER_COUNTS_16];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_17[STAGE_TOWER_COUNTS_17];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_18[STAGE_TOWER_COUNTS_18];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_19[STAGE_TOWER_COUNTS_19];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_20[STAGE_TOWER_COUNTS_20];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_21[STAGE_TOWER_COUNTS_21];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_22[STAGE_TOWER_COUNTS_22];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_23[STAGE_TOWER_COUNTS_23];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_24[STAGE_TOWER_COUNTS_24];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_25[STAGE_TOWER_COUNTS_25];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_26[STAGE_TOWER_COUNTS_26];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_27[STAGE_TOWER_COUNTS_27];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_28[STAGE_TOWER_COUNTS_28];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_29[STAGE_TOWER_COUNTS_29];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_30[STAGE_TOWER_COUNTS_30];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_31[STAGE_TOWER_COUNTS_31];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_32[STAGE_TOWER_COUNTS_32];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_33[STAGE_TOWER_COUNTS_33];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_34[STAGE_TOWER_COUNTS_34];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_35[STAGE_TOWER_COUNTS_35];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_36[STAGE_TOWER_COUNTS_36];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_37[STAGE_TOWER_COUNTS_37];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_38[STAGE_TOWER_COUNTS_38];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_39[STAGE_TOWER_COUNTS_39];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_40[STAGE_TOWER_COUNTS_40];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_41[STAGE_TOWER_COUNTS_41];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_42[STAGE_TOWER_COUNTS_42];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_43[STAGE_TOWER_COUNTS_43];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_44[STAGE_TOWER_COUNTS_44];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_45[STAGE_TOWER_COUNTS_45];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_46[STAGE_TOWER_COUNTS_46];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_47[STAGE_TOWER_COUNTS_47];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_48[STAGE_TOWER_COUNTS_48];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_49[STAGE_TOWER_COUNTS_49];

//BossEnemy
typedef struct _battleBossEnemyInfo
{
    int level;
    int duration;
}BattleBossEnemyInfo;

extern BattleBossEnemyInfo s_battleBossEnemyInfo[STAGE_COUNT];

#endif /* defined(__BlackWings__EnemyDispatchConfig__) */
