//
//  EnemyDispatchConfig.h
//  BlackWings
//
//  Created by Jacky on 14-6-29.
//
//

#ifndef __BlackWings__EnemyDispatchConfig__
#define __BlackWings__EnemyDispatchConfig__

#include "Configuration.h"

//normal enemy waves
#define STAGE_ENEMY_WAVES_SPC_00 1
#define STAGE_ENEMY_WAVES_SPC_01 2
#define STAGE_ENEMY_WAVES_SPC_02 2
#define STAGE_ENEMY_WAVES_SPC_03 3
#define STAGE_ENEMY_WAVES_SPC_04 3
#define STAGE_ENEMY_WAVES_SPC_05 3
#define STAGE_ENEMY_WAVES_SPC_06 3
#define STAGE_ENEMY_WAVES_SPC_07 3
#define STAGE_ENEMY_WAVES_SPC_08 3
#define STAGE_ENEMY_WAVES_SPC_09 3
#define STAGE_ENEMY_WAVES_SPC_10 3
#define STAGE_ENEMY_WAVES_SPC_11 5
#define STAGE_ENEMY_WAVES_SPC_12 3
#define STAGE_ENEMY_WAVES_SPC_13 3
#define STAGE_ENEMY_WAVES_SPC_14 3
#define STAGE_ENEMY_WAVES_SPC_15 3
#define STAGE_ENEMY_WAVES_SPC_16 3
#define STAGE_ENEMY_WAVES_SPC_17 3
#define STAGE_ENEMY_WAVES_SPC_18 3
#define STAGE_ENEMY_WAVES_SPC_19 3
#define STAGE_ENEMY_WAVES_SPC_20 3
#define STAGE_ENEMY_WAVES_SPC_21 3
#define STAGE_ENEMY_WAVES_SPC_22 3
#define STAGE_ENEMY_WAVES_SPC_23 3
#define STAGE_ENEMY_WAVES_SPC_24 3
#define STAGE_ENEMY_WAVES_SPC_25 3
#define STAGE_ENEMY_WAVES_SPC_26 3
#define STAGE_ENEMY_WAVES_SPC_27 3
#define STAGE_ENEMY_WAVES_SPC_28 3
#define STAGE_ENEMY_WAVES_SPC_29 3
#define STAGE_ENEMY_WAVES_SPC_30 3
#define STAGE_ENEMY_WAVES_SPC_31 3
#define STAGE_ENEMY_WAVES_SPC_32 3
#define STAGE_ENEMY_WAVES_SPC_33 3
#define STAGE_ENEMY_WAVES_SPC_34 3
#define STAGE_ENEMY_WAVES_SPC_35 3
#define STAGE_ENEMY_WAVES_SPC_36 3
#define STAGE_ENEMY_WAVES_SPC_37 3
#define STAGE_ENEMY_WAVES_SPC_38 3
#define STAGE_ENEMY_WAVES_SPC_39 3
#define STAGE_ENEMY_WAVES_SPC_40 3
#define STAGE_ENEMY_WAVES_SPC_41 3
#define STAGE_ENEMY_WAVES_SPC_42 3
#define STAGE_ENEMY_WAVES_SPC_43 3
#define STAGE_ENEMY_WAVES_SPC_44 3
#define STAGE_ENEMY_WAVES_SPC_45 3
#define STAGE_ENEMY_WAVES_SPC_46 3
#define STAGE_ENEMY_WAVES_SPC_47 3
#define STAGE_ENEMY_WAVES_SPC_48 3
#define STAGE_ENEMY_WAVES_SPC_49 3

#define STAGE_ENEMY_WAVES_LOOP_00 1
#define STAGE_ENEMY_WAVES_LOOP_01 2
#define STAGE_ENEMY_WAVES_LOOP_02 2
#define STAGE_ENEMY_WAVES_LOOP_03 3
#define STAGE_ENEMY_WAVES_LOOP_04 3
#define STAGE_ENEMY_WAVES_LOOP_05 3
#define STAGE_ENEMY_WAVES_LOOP_06 3
#define STAGE_ENEMY_WAVES_LOOP_07 3
#define STAGE_ENEMY_WAVES_LOOP_08 3
#define STAGE_ENEMY_WAVES_LOOP_09 3
#define STAGE_ENEMY_WAVES_LOOP_10 3
#define STAGE_ENEMY_WAVES_LOOP_11 5
#define STAGE_ENEMY_WAVES_LOOP_12 3
#define STAGE_ENEMY_WAVES_LOOP_13 3
#define STAGE_ENEMY_WAVES_LOOP_14 3
#define STAGE_ENEMY_WAVES_LOOP_15 3
#define STAGE_ENEMY_WAVES_LOOP_16 3
#define STAGE_ENEMY_WAVES_LOOP_17 3
#define STAGE_ENEMY_WAVES_LOOP_18 3
#define STAGE_ENEMY_WAVES_LOOP_19 3
#define STAGE_ENEMY_WAVES_LOOP_20 3
#define STAGE_ENEMY_WAVES_LOOP_21 3
#define STAGE_ENEMY_WAVES_LOOP_22 3
#define STAGE_ENEMY_WAVES_LOOP_23 3
#define STAGE_ENEMY_WAVES_LOOP_24 3
#define STAGE_ENEMY_WAVES_LOOP_25 3
#define STAGE_ENEMY_WAVES_LOOP_26 3
#define STAGE_ENEMY_WAVES_LOOP_27 3
#define STAGE_ENEMY_WAVES_LOOP_28 3
#define STAGE_ENEMY_WAVES_LOOP_29 3
#define STAGE_ENEMY_WAVES_LOOP_30 3
#define STAGE_ENEMY_WAVES_LOOP_31 3
#define STAGE_ENEMY_WAVES_LOOP_32 3
#define STAGE_ENEMY_WAVES_LOOP_33 3
#define STAGE_ENEMY_WAVES_LOOP_34 3
#define STAGE_ENEMY_WAVES_LOOP_35 3
#define STAGE_ENEMY_WAVES_LOOP_36 3
#define STAGE_ENEMY_WAVES_LOOP_37 3
#define STAGE_ENEMY_WAVES_LOOP_38 3
#define STAGE_ENEMY_WAVES_LOOP_39 3
#define STAGE_ENEMY_WAVES_LOOP_40 3
#define STAGE_ENEMY_WAVES_LOOP_41 3
#define STAGE_ENEMY_WAVES_LOOP_42 3
#define STAGE_ENEMY_WAVES_LOOP_43 3
#define STAGE_ENEMY_WAVES_LOOP_44 3
#define STAGE_ENEMY_WAVES_LOOP_45 3
#define STAGE_ENEMY_WAVES_LOOP_46 3
#define STAGE_ENEMY_WAVES_LOOP_47 3
#define STAGE_ENEMY_WAVES_LOOP_48 3
#define STAGE_ENEMY_WAVES_LOOP_49 3

//towerCount
#define STAGE_TOWER_COUNTS_00 1
#define STAGE_TOWER_COUNTS_01 1
#define STAGE_TOWER_COUNTS_02 2
#define STAGE_TOWER_COUNTS_03 2
#define STAGE_TOWER_COUNTS_04 3
#define STAGE_TOWER_COUNTS_05 5
#define STAGE_TOWER_COUNTS_06 5
#define STAGE_TOWER_COUNTS_07 5
#define STAGE_TOWER_COUNTS_08 5
#define STAGE_TOWER_COUNTS_09 6
#define STAGE_TOWER_COUNTS_10 6
#define STAGE_TOWER_COUNTS_11 8
#define STAGE_TOWER_COUNTS_12 7
#define STAGE_TOWER_COUNTS_13 7
#define STAGE_TOWER_COUNTS_14 8
#define STAGE_TOWER_COUNTS_15 8
#define STAGE_TOWER_COUNTS_16 9
#define STAGE_TOWER_COUNTS_17 8
#define STAGE_TOWER_COUNTS_18 10
#define STAGE_TOWER_COUNTS_19 8
#define STAGE_TOWER_COUNTS_20 2
#define STAGE_TOWER_COUNTS_21 2
#define STAGE_TOWER_COUNTS_22 2
#define STAGE_TOWER_COUNTS_23 2
#define STAGE_TOWER_COUNTS_24 2
#define STAGE_TOWER_COUNTS_25 2
#define STAGE_TOWER_COUNTS_26 2
#define STAGE_TOWER_COUNTS_27 2
#define STAGE_TOWER_COUNTS_28 2
#define STAGE_TOWER_COUNTS_29 2
#define STAGE_TOWER_COUNTS_30 2
#define STAGE_TOWER_COUNTS_31 2
#define STAGE_TOWER_COUNTS_32 2
#define STAGE_TOWER_COUNTS_33 2
#define STAGE_TOWER_COUNTS_34 2
#define STAGE_TOWER_COUNTS_35 2
#define STAGE_TOWER_COUNTS_36 2
#define STAGE_TOWER_COUNTS_37 2
#define STAGE_TOWER_COUNTS_38 2
#define STAGE_TOWER_COUNTS_39 2
#define STAGE_TOWER_COUNTS_40 2
#define STAGE_TOWER_COUNTS_41 2
#define STAGE_TOWER_COUNTS_42 2
#define STAGE_TOWER_COUNTS_43 2
#define STAGE_TOWER_COUNTS_44 2
#define STAGE_TOWER_COUNTS_45 2
#define STAGE_TOWER_COUNTS_46 2
#define STAGE_TOWER_COUNTS_47 2
#define STAGE_TOWER_COUNTS_48 2
#define STAGE_TOWER_COUNTS_49 2

//NormalEnemy
typedef struct _battleNormalEnemyConfig
{
    int duration;
    int type;
    int level;
    int count_lower;
    int count_upper;
}BattleNormalEnemyConfig;

typedef struct _battleNormalEnemyInfo
{
    BattleNormalEnemyConfig* bnec_spc;
    int waves_spc;
    BattleNormalEnemyConfig* bnec_loop;
    int waves_loop;
}BattleNormalEnemyInfo;

extern BattleNormalEnemyInfo s_battleNormalEnemyInfo[STAGE_COUNT];

//spcial enemy
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_0[STAGE_ENEMY_WAVES_SPC_00];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_1[STAGE_ENEMY_WAVES_SPC_01];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_2[STAGE_ENEMY_WAVES_SPC_02];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_3[STAGE_ENEMY_WAVES_SPC_03];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_4[STAGE_ENEMY_WAVES_SPC_04];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_5[STAGE_ENEMY_WAVES_SPC_05];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_6[STAGE_ENEMY_WAVES_SPC_06];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_7[STAGE_ENEMY_WAVES_SPC_07];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_8[STAGE_ENEMY_WAVES_SPC_08];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_9[STAGE_ENEMY_WAVES_SPC_09];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_10[STAGE_ENEMY_WAVES_SPC_10];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_11[STAGE_ENEMY_WAVES_SPC_11];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_12[STAGE_ENEMY_WAVES_SPC_12];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_13[STAGE_ENEMY_WAVES_SPC_13];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_14[STAGE_ENEMY_WAVES_SPC_14];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_15[STAGE_ENEMY_WAVES_SPC_15];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_16[STAGE_ENEMY_WAVES_SPC_16];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_17[STAGE_ENEMY_WAVES_SPC_17];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_18[STAGE_ENEMY_WAVES_SPC_18];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_19[STAGE_ENEMY_WAVES_SPC_19];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_20[STAGE_ENEMY_WAVES_SPC_20];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_21[STAGE_ENEMY_WAVES_SPC_21];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_22[STAGE_ENEMY_WAVES_SPC_22];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_23[STAGE_ENEMY_WAVES_SPC_23];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_24[STAGE_ENEMY_WAVES_SPC_24];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_25[STAGE_ENEMY_WAVES_SPC_25];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_26[STAGE_ENEMY_WAVES_SPC_26];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_27[STAGE_ENEMY_WAVES_SPC_27];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_28[STAGE_ENEMY_WAVES_SPC_28];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_29[STAGE_ENEMY_WAVES_SPC_29];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_30[STAGE_ENEMY_WAVES_SPC_30];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_31[STAGE_ENEMY_WAVES_SPC_31];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_32[STAGE_ENEMY_WAVES_SPC_32];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_33[STAGE_ENEMY_WAVES_SPC_33];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_34[STAGE_ENEMY_WAVES_SPC_34];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_35[STAGE_ENEMY_WAVES_SPC_35];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_36[STAGE_ENEMY_WAVES_SPC_36];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_37[STAGE_ENEMY_WAVES_SPC_37];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_38[STAGE_ENEMY_WAVES_SPC_38];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_39[STAGE_ENEMY_WAVES_SPC_39];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_40[STAGE_ENEMY_WAVES_SPC_40];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_41[STAGE_ENEMY_WAVES_SPC_41];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_42[STAGE_ENEMY_WAVES_SPC_42];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_43[STAGE_ENEMY_WAVES_SPC_43];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_44[STAGE_ENEMY_WAVES_SPC_44];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_45[STAGE_ENEMY_WAVES_SPC_45];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_46[STAGE_ENEMY_WAVES_SPC_46];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_47[STAGE_ENEMY_WAVES_SPC_47];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_48[STAGE_ENEMY_WAVES_SPC_48];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Spc_49[STAGE_ENEMY_WAVES_SPC_49];

//loop enemy
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_0[STAGE_ENEMY_WAVES_LOOP_00];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_1[STAGE_ENEMY_WAVES_LOOP_01];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_2[STAGE_ENEMY_WAVES_LOOP_02];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_3[STAGE_ENEMY_WAVES_LOOP_03];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_4[STAGE_ENEMY_WAVES_LOOP_04];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_5[STAGE_ENEMY_WAVES_LOOP_05];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_6[STAGE_ENEMY_WAVES_LOOP_06];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_7[STAGE_ENEMY_WAVES_LOOP_07];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_8[STAGE_ENEMY_WAVES_LOOP_08];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_9[STAGE_ENEMY_WAVES_LOOP_09];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_10[STAGE_ENEMY_WAVES_LOOP_10];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_11[STAGE_ENEMY_WAVES_LOOP_11];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_12[STAGE_ENEMY_WAVES_LOOP_12];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_13[STAGE_ENEMY_WAVES_LOOP_13];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_14[STAGE_ENEMY_WAVES_LOOP_14];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_15[STAGE_ENEMY_WAVES_LOOP_15];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_16[STAGE_ENEMY_WAVES_LOOP_16];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_17[STAGE_ENEMY_WAVES_LOOP_17];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_18[STAGE_ENEMY_WAVES_LOOP_18];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_19[STAGE_ENEMY_WAVES_LOOP_19];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_20[STAGE_ENEMY_WAVES_LOOP_20];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_21[STAGE_ENEMY_WAVES_LOOP_21];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_22[STAGE_ENEMY_WAVES_LOOP_22];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_23[STAGE_ENEMY_WAVES_LOOP_23];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_24[STAGE_ENEMY_WAVES_LOOP_24];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_25[STAGE_ENEMY_WAVES_LOOP_25];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_26[STAGE_ENEMY_WAVES_LOOP_26];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_27[STAGE_ENEMY_WAVES_LOOP_27];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_28[STAGE_ENEMY_WAVES_LOOP_28];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_29[STAGE_ENEMY_WAVES_LOOP_29];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_30[STAGE_ENEMY_WAVES_LOOP_30];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_31[STAGE_ENEMY_WAVES_LOOP_31];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_32[STAGE_ENEMY_WAVES_LOOP_32];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_33[STAGE_ENEMY_WAVES_LOOP_33];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_34[STAGE_ENEMY_WAVES_LOOP_34];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_35[STAGE_ENEMY_WAVES_LOOP_35];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_36[STAGE_ENEMY_WAVES_LOOP_36];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_37[STAGE_ENEMY_WAVES_LOOP_37];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_38[STAGE_ENEMY_WAVES_LOOP_38];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_39[STAGE_ENEMY_WAVES_LOOP_39];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_40[STAGE_ENEMY_WAVES_LOOP_40];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_41[STAGE_ENEMY_WAVES_LOOP_41];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_42[STAGE_ENEMY_WAVES_LOOP_42];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_43[STAGE_ENEMY_WAVES_LOOP_43];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_44[STAGE_ENEMY_WAVES_LOOP_44];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_45[STAGE_ENEMY_WAVES_LOOP_45];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_46[STAGE_ENEMY_WAVES_LOOP_46];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_47[STAGE_ENEMY_WAVES_LOOP_47];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_48[STAGE_ENEMY_WAVES_LOOP_48];
extern BattleNormalEnemyConfig s_battleNormalEnemyConfig_Loop_49[STAGE_ENEMY_WAVES_LOOP_49];

//TowerEnemy
typedef struct _battleTowerEnemyConfig
{
    int level;
    int x;
    int y;
}BattleTowerEnemyConfig;

typedef struct _battleTowerEnemyInfo
{
    BattleTowerEnemyConfig* _btec;
    int counts;
}BattleTowerEnemyInfo;

extern BattleTowerEnemyInfo s_battleTowerEnemyInfo[STAGE_COUNT];

extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_0[STAGE_TOWER_COUNTS_00];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_1[STAGE_TOWER_COUNTS_01];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_2[STAGE_TOWER_COUNTS_02];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_3[STAGE_TOWER_COUNTS_03];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_4[STAGE_TOWER_COUNTS_04];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_5[STAGE_TOWER_COUNTS_05];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_6[STAGE_TOWER_COUNTS_06];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_7[STAGE_TOWER_COUNTS_07];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_8[STAGE_TOWER_COUNTS_08];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_9[STAGE_TOWER_COUNTS_09];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_10[STAGE_TOWER_COUNTS_10];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_11[STAGE_TOWER_COUNTS_11];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_12[STAGE_TOWER_COUNTS_12];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_13[STAGE_TOWER_COUNTS_13];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_14[STAGE_TOWER_COUNTS_14];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_15[STAGE_TOWER_COUNTS_15];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_16[STAGE_TOWER_COUNTS_16];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_17[STAGE_TOWER_COUNTS_17];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_18[STAGE_TOWER_COUNTS_18];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_19[STAGE_TOWER_COUNTS_19];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_20[STAGE_TOWER_COUNTS_20];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_21[STAGE_TOWER_COUNTS_21];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_22[STAGE_TOWER_COUNTS_22];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_23[STAGE_TOWER_COUNTS_23];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_24[STAGE_TOWER_COUNTS_24];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_25[STAGE_TOWER_COUNTS_25];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_26[STAGE_TOWER_COUNTS_26];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_27[STAGE_TOWER_COUNTS_27];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_28[STAGE_TOWER_COUNTS_28];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_29[STAGE_TOWER_COUNTS_29];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_30[STAGE_TOWER_COUNTS_30];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_31[STAGE_TOWER_COUNTS_31];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_32[STAGE_TOWER_COUNTS_32];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_33[STAGE_TOWER_COUNTS_33];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_34[STAGE_TOWER_COUNTS_34];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_35[STAGE_TOWER_COUNTS_35];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_36[STAGE_TOWER_COUNTS_36];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_37[STAGE_TOWER_COUNTS_37];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_38[STAGE_TOWER_COUNTS_38];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_39[STAGE_TOWER_COUNTS_39];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_40[STAGE_TOWER_COUNTS_40];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_41[STAGE_TOWER_COUNTS_41];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_42[STAGE_TOWER_COUNTS_42];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_43[STAGE_TOWER_COUNTS_43];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_44[STAGE_TOWER_COUNTS_44];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_45[STAGE_TOWER_COUNTS_45];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_46[STAGE_TOWER_COUNTS_46];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_47[STAGE_TOWER_COUNTS_47];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_48[STAGE_TOWER_COUNTS_48];
extern BattleTowerEnemyConfig s_battleTowerEnemyConfig_49[STAGE_TOWER_COUNTS_49];

#define NO_BOSS 0
//BossEnemy
typedef struct _battleBossEnemyInfo
{
    int level;
    int duration;
}BattleBossEnemyInfo;

extern BattleBossEnemyInfo s_battleBossEnemyInfo[STAGE_COUNT];

#endif /* defined(__BlackWings__EnemyDispatchConfig__) */
